name: Android Release Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Release APK with Keystore
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Decode Keystore File
        run: |
          echo "${{ secrets.KEYSTORE_FILE_BASE64 }}" | base64 --decode > release-keystore.jks

      - name: Configure Gradle Signing
        run: |
          echo "
          android {
              signingConfigs {
                  create("release") {
                      storeFile file('release-keystore.jks')
                      storePassword '${{ secrets.KEYSTORE_PASSWORD }}'
                      keyAlias '${{ secrets.KEY_ALIAS }}'
                      keyPassword '${{ secrets.KEY_PASSWORD }}'
                  }
              }
              buildTypes {
                   getByName("release") {
                      signingConfig signingConfigs.release
                  }
              }
          }" >> app/release-signing.gradle

      - name: Include Signing in build.gradle
        run: |
          echo "apply from: 'app/release-signing.gradle'" >> app/build.gradle

      - name: Make gradlew Executable
        run: chmod +x ./gradlew

      - name: Build Signed Release APK
        run: ./gradlew assembleRelease

      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk
